# Generated by Django 2.0.1 on 2018-03-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=32)),
                ('subject_comments', models.TextField(null=True)),
                ('subject_grade', models.IntegerField(null=True)),
                ('subject_stars', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=32)),
                ('teacher_subject', models.ForeignKey(on_delete='CASCADE', to='comment.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('user_id', models.CharField(max_length=32)),
                ('use_grade', models.IntegerField()),
            ],
        ),
    ]
