# Generated by Django 2.0.1 on 2018-03-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_teacher',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to='comment.Teacher'),
            preserve_default=False,
        ),
    ]
